language: node_js
sudo: false
node_js:
   - "0.12.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install
  - npm test
after_script:
  - grunt coveralls